on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      run: echo The Title of your PR is ${{ toJson(github) }}