on:
  pull_request:
    types: [opened, synchronize]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ github.event.pull_request.title }}
      run: |
        echo "$GITHUB_CONTEXT"