name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: PR title validation
        if: ${{github.event.pull_request.title != 'Release' }}
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
        # uses: aslafy-z/conventional-pr-title-action@v3
        # env:
        #   GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}