name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    if: github.head_commit.message != 'Release'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: PR title validation
        uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}
