name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    - name: Show default environment variables
      run: |
          echo "The job_id is: $GITHUB_JOB"
    if: github.event.head_commit.message != 'Release'
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}
