name: Release
on:
  push:
    branches:
      - uat
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18.17.1
      - run: yarn install --frozen-lockfile
      - run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  backmerge-uat:
    needs: release
    if: endsWith(github.ref, '/uat')
    uses: ./.github/workflows/backmerge_to_lower_branch.yml@main
    name: Backmerge uat
    with:
      BRANCH_TO_UPDATE: dev
    secrets:
      PAT: ${{ secrets.TODO_GITHUB_TOKEN }}
  backmerge-main:
    needs: release
    if: endsWith(github.ref, '/main')
    uses: ./.github/workflows/automerge.yml@main
    name: Backmerge main
    secrets:
      PAT: ${{ secrets.TODO_GITHUB_TOKEN }}
