name: Release
on:
  push:
    branches:
      - dev
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 17
      - run: yarn install --frozen-lockfile
      - run: npx semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.TODO_GITHUB_TOKEN }}
